services:
  postgres:
    image: postgres:15-alpine
    container_name: warehouse_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: warehouse_db
    ports:
      - "5434:5432"
    volumes:
      - warehouse_data:/var/lib/postgresql/data

volumes:
  warehouse_data:
